"use client";

import { useRef, useState } from "react";
import { ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, ChevronDown, Leaf, Menu, MessageCircle, PackageCheck, Play, X } from "lucide-react";

const phone = "2348032052940";
const whatsapp = (subject = "Crunchy Kuli-Kuli") => `https://wa.me/${phone}?text=${encodeURIComponent(`Hello OUNJEEH, I'd like to enquire about ${subject}.`)}`;
const products = [
  { eyebrow: "01 / THE ORIGINAL", title: "Crunchy Kuli-Kuli", descriptor: "A proper groundnut crunch.", copy: "Richly satisfying, made from carefully processed groundnuts and packed for whenever a little crunch sounds good.", note: "Available in convenient pouches", image: "/media/kulikuli-pouches.jpg", alt: "OUNJEEH Crunchy Kuli-Kuli packed in clear pouches with the original red label", subject: "your Crunchy Kuli-Kuli pouches" },
  { eyebrow: "02 / THE CRUNCH", title: "Made to share", descriptor: "Bring a bowl. Bring your people.", copy: "A generous bowl of the same unmistakable groundnut flavour, ready for sharing, snacking and the moments in between.", note: "Ask about pack options", image: "/media/kulikuli-bowl.jpg", alt: "A large bowl filled with freshly made OUNJEEH Kuli-Kuli", subject: "Kuli-Kuli for sharing" },
  { eyebrow: "03 / THE BIGGER ORDER", title: "For the whole crew", descriptor: "More of the good stuff.", copy: "Planning for a shop, a gathering or a bigger household? Talk to us about our carton and bulk order options.", note: "Carton enquiries welcome", image: "/media/kulikuli-cartons.jpg", alt: "Cartons of OUNJEEH Crunchy Kuli-Kuli prepared for larger orders", subject: "carton or bulk Kuli-Kuli orders" },
];
const steps = [
  { number: "01", title: "Good groundnuts", copy: "We start with the ingredient that gives every bite its character." },
  { number: "02", title: "Careful preparation", copy: "The groundnuts are processed and seasoned for a distinctive taste." },
  { number: "03", title: "That signature crunch", copy: "Each batch is made into the crisp Kuli-Kuli you know and love." },
  { number: "04", title: "Packed for you", copy: "We pack it up and get it ready for its next stop: your hands." },
];
const clips = [
  { label: "A look behind the scenes", file: "/media/making.mp4", poster: "/media/making-poster.jpg" },
  { label: "Freshly packed", file: "/media/packing.mp4", poster: "/media/packing-poster.jpg" },
];
const faqs = [
  { q: "How do I order?", a: "Tap any order or enquiry button on this page to chat with OUNJEEH on WhatsApp. Tell us what you’d like and we’ll help you from there." },
  { q: "Can I ask about a bulk order?", a: "Yes. We have carton and bulk options. Send us a WhatsApp message with the quantity you have in mind so we can discuss availability." },
  { q: "Do you also have groundnut oil?", a: "Yes. You can ask us about OUNJEEH groundnut oil through the product link above or via WhatsApp." },
];

function Brand({ light = false }: { light?: boolean }) {
  return <a href="#top" className={`brand ${light ? "brand-light" : ""}`} aria-label="OUNJEEH home"><img className="brand-logo" src="/ounjeeh-logo.png" alt="OUNJEEH logo" /></a>;
}

export default function Home() {
  const [current, setCurrent] = useState(0);
  const [menuOpen, setMenuOpen] = useState(false);
  const [clip, setClip] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const startX = useRef<number | null>(null);
  const changeProduct = (direction: number) => setCurrent((i) => (i + direction + products.length) % products.length);
  const selectClip = (index: number) => { if (index === clip) return; videoRef.current?.pause(); setPlaying(false); setClip(index); };
  const playVideo = () => { videoRef.current?.play().then(() => setPlaying(true)).catch(() => setPlaying(false)); };

  return <>
    <header className="site-header" id="top"><div className="header-inner shell"><Brand /><nav className={`main-nav ${menuOpen ? "main-nav-open" : ""}`} aria-label="Main navigation"><a onClick={() => setMenuOpen(false)} href="#products">The Kuli-Kuli</a><a onClick={() => setMenuOpen(false)} href="#why">Why we love it</a><a onClick={() => setMenuOpen(false)} href="#process">Our process</a><a onClick={() => setMenuOpen(false)} href="#story">Our story</a></nav><div className="header-actions"><a className="button button-dark header-order" href={whatsapp()} target="_blank" rel="noopener noreferrer">Order on WhatsApp <ArrowUpRight size={16} /></a><button type="button" className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Close menu" : "Open menu"} aria-expanded={menuOpen}>{menuOpen ? <X size={23} /> : <Menu size={23} />}</button></div></div></header>

    <main>
      <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><div className="hero-copy-inner"><span className="eyebrow"><span className="eyebrow-line" /> NIGERIAN ROOTS. REAL CRUNCH.</span><h1 id="hero-title">Crunch into <em>something</em> naturally good.</h1><p>Meet the Kuli-Kuli that makes every snack break worth taking. Groundnut goodness, a satisfying crunch, and a taste that feels like home.</p><div className="hero-buttons"><a href="#products" className="button button-dark">Explore the Kuli-Kuli <ArrowDownRight size={18} /></a><a href="#process" className="text-link">See how it’s made <ArrowUpRight size={17} /></a></div><div className="hero-proof"><span className="proof-spark">✳</span><span>Made with groundnuts<br /><strong>Made to be enjoyed.</strong></span></div></div></div><div className="hero-visual"><img src="/media/kulikuli-pouches.jpg" alt="Close view of OUNJEEH Crunchy Kuli-Kuli in its original packaging" fetchPriority="high" /><span className="hero-image-shade" aria-hidden="true" /><span className="hero-vertical" aria-hidden="true">THE TASTE OF A GOOD MOMENT</span><div className="hero-stamp" aria-hidden="true"><span>100%</span><small>GOOD<br />CRUNCH</small></div><span className="hero-image-caption">THE ORIGINAL CRUNCHY KULI-KULI <span>↗</span></span></div></section>
      <div className="marquee" aria-hidden="true"><div className="marquee-inner">GOOD FOOD <span>✳</span> GOOD MOOD <span>✳</span> GREAT CRUNCH <span>✳</span> GOOD FOOD <span>✳</span> GOOD MOOD <span>✳</span> GREAT CRUNCH <span>✳</span></div></div>
      <section className="products-section section-pad" id="products" aria-labelledby="products-title"><div className="shell"><div className="section-head"><div><p className="kicker">THE GOOD STUFF</p><h2 id="products-title">Get to know<br /><em>your next crunch.</em></h2></div><p>One irresistible favourite. A few ways to enjoy it. Find the option that fits your moment.</p></div><div className="product-explorer" aria-label="Explore Kuli-Kuli options" onTouchStart={(event) => { startX.current = event.touches[0]?.clientX ?? null; }} onTouchEnd={(event) => { if (startX.current === null) return; const dx = (event.changedTouches[0]?.clientX ?? startX.current) - startX.current; if (Math.abs(dx) > 60) changeProduct(dx < 0 ? 1 : -1); startX.current = null; }} onKeyDown={(event) => { if (event.target === event.currentTarget) { if (event.key === "ArrowRight") changeProduct(1); if (event.key === "ArrowLeft") changeProduct(-1); } }} tabIndex={0}><div className="product-image" key={products[current].image}><img src={products[current].image} alt={products[current].alt} loading="lazy" /><div className="photo-number">0{current + 1}<span> / 0{products.length}</span></div></div><div className="product-detail" aria-live="polite"><div className="detail-top"><span>{products[current].eyebrow}</span><span className="detail-icon">✳</span></div><div className="detail-body"><p className="detail-script">The real deal</p><h3>{products[current].title}</h3><p className="detail-descriptor">{products[current].descriptor}</p><p className="detail-copy">{products[current].copy}</p><div className="detail-note"><PackageCheck size={20} /><span>{products[current].note}</span></div></div><div className="detail-bottom"><a href={whatsapp(products[current].subject)} target="_blank" rel="noopener noreferrer" className="button button-cream">Ask about this option <ArrowUpRight size={18} /></a><div className="carousel-arrows"><button type="button" onClick={() => changeProduct(-1)} aria-label="Previous product"><ArrowLeft size={20} /></button><button type="button" onClick={() => changeProduct(1)} aria-label="Next product"><ArrowRight size={20} /></button></div></div></div></div><div className="product-selector" aria-label="Choose a product view">{products.map((item, index) => <button key={item.eyebrow} type="button" className={index === current ? "selected" : ""} onClick={() => setCurrent(index)} aria-label={`Show ${item.title}, view ${index + 1}`} aria-current={index === current ? "true" : undefined}><span>0{index + 1}</span> {item.title}</button>)}</div></div></section>
      <section className="benefits-section section-pad" id="why" aria-labelledby="benefits-title"><div className="shell benefits-grid"><div className="benefits-intro"><p className="kicker kicker-gold">WHAT MAKES IT GOOD</p><h2 id="benefits-title">The little things that make a <em>big crunch.</em></h2><p>A familiar Nigerian favourite, made with care and ready for whatever the day brings.</p><a href={whatsapp()} className="underlined-link" target="_blank" rel="noopener noreferrer">Let’s get you some <ArrowUpRight size={18} /></a></div><div className="benefit-cards"><div className="benefit"><span className="benefit-number">01</span><span className="benefit-symbol">✳</span><h3>Groundnut goodness</h3><p>That deep, satisfying groundnut taste at the heart of every bite.</p></div><div className="benefit"><span className="benefit-number">02</span><Leaf className="benefit-symbol" size={34} strokeWidth={1.4} /><h3>Real ingredients</h3><p>Carefully made from groundnuts for an authentic taste of home.</p></div><div className="benefit"><span className="benefit-number">03</span><span className="benefit-symbol">↗</span><h3>The perfect crunch</h3><p>Crisp, full of character, and ready whenever the craving hits.</p></div><div className="benefit"><span className="benefit-number">04</span><PackageCheck className="benefit-symbol" size={34} strokeWidth={1.4} /><h3>Ready to go</h3><p>Conveniently packed, with options for snacking, sharing and bigger orders.</p></div></div></div></section>
      <section className="process-section section-pad" id="process" aria-labelledby="process-title"><div className="shell"><div className="process-heading"><div><p className="kicker">BEHIND THE CRUNCH</p><h2 id="process-title">From groundnut<br />to <em>goodness.</em></h2></div><p>A closer look at the hands and care behind OUNJEEH Kuli-Kuli.</p></div><div className="story-media"><div className="video-stage"><video key={clips[clip].file} ref={videoRef} src={clips[clip].file} poster={clips[clip].poster} controls={playing} playsInline preload="none" aria-label={clips[clip].label} onEnded={() => setPlaying(false)} />{!playing && <button type="button" className="video-play" onClick={playVideo} aria-label={`Play video: ${clips[clip].label}`}><Play size={23} fill="currentColor" /></button>}<div className="video-overlay-label">A LITTLE LOOK BEHIND THE SCENES</div></div><aside className="video-aside"><div><span className="aside-flower">✳</span><p>Good food has a story.</p><h3>Here’s a bit of ours.</h3></div><div className="clip-selector" aria-label="Choose a video">{clips.map((item, index) => <button type="button" key={item.file} onClick={() => selectClip(index)} className={clip === index ? "active" : ""} aria-pressed={clip === index}><span>0{index + 1}</span>{item.label}<ArrowUpRight size={17} /></button>)}</div></aside></div><div className="process-steps">{steps.map((step) => <div className="process-step" key={step.number}><span>{step.number}</span><h3>{step.title}</h3><p>{step.copy}</p></div>)}</div></div></section>
      <section className="editorial" id="story" aria-labelledby="story-title"><div className="editorial-photo"><img src="/media/kulikuli-making.jpg" alt="An OUNJEEH team member holding a bowl of freshly made Kuli-Kuli" loading="lazy" /><span>MADE WITH CARE IN NIGERIA</span></div><div className="editorial-copy"><p className="kicker">MEET OUNJEEH</p><h2 id="story-title">Good food.<br /><em>Better living.</em></h2><p>At OUNJEEH, we believe good food should be easier to enjoy. Our Crunchy Kuli-Kuli brings a much-loved Nigerian snack to your everyday moments, with the taste and texture that keep you coming back.</p><p>From our hands to yours, every pack is an invitation to slow down and enjoy the good stuff.</p><a className="button button-dark" target="_blank" rel="noopener noreferrer" href={whatsapp("OUNJEEH Kuli-Kuli")}>Say hello on WhatsApp <ArrowUpRight size={18} /></a></div></section>
      <section className="range-section section-pad" aria-labelledby="range-title"><div className="shell"><div className="range-heading"><p className="kicker">MORE TO EXPLORE</p><h2 id="range-title">From our kitchen<br /><em>to yours.</em></h2></div><div className="range-grid"><article className="range-card"><div className="range-image"><img src="/media/kulikuli-bowl.jpg" alt="A bowl of OUNJEEH Crunchy Kuli-Kuli" loading="lazy" /></div><div className="range-card-content"><span>THE EVERYDAY FAVOURITE</span><h3>Crunchy Kuli-Kuli</h3><a href={whatsapp("Crunchy Kuli-Kuli")} target="_blank" rel="noopener noreferrer" aria-label="Enquire about Crunchy Kuli-Kuli"><ArrowUpRight size={20} /></a></div></article><article className="range-card"><div className="range-image"><img src="/media/groundnut-oil.jpg" alt="A bottle of OUNJEEH premium groundnut oil" loading="lazy" /></div><div className="range-card-content"><span>ANOTHER GROUNDNUT GOODIE</span><h3>Groundnut oil</h3><a href={whatsapp("your groundnut oil")} target="_blank" rel="noopener noreferrer" aria-label="Enquire about groundnut oil"><ArrowUpRight size={20} /></a></div></article></div></div></section>
      <section className="faq-section section-pad" aria-labelledby="faq-title"><div className="shell faq-grid"><div><p className="kicker">A FEW GOOD ANSWERS</p><h2 id="faq-title">Curious?<br /><em>We’ve got you.</em></h2><p>For anything else, just send us a message.</p></div><div className="faq-list">{faqs.map((item, index) => <div className="faq-item" key={item.q}><button type="button" aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? null : index)}>{item.q}<ChevronDown size={19} /></button>{openFaq === index && <p>{item.a}</p>}</div>)}</div></div></section>
      <section className="final-cta"><div className="final-cta-shade" /><img src="/media/kulikuli-bowl.jpg" alt="A generous bowl of OUNJEEH Kuli-Kuli ready to enjoy" loading="lazy" /><div className="shell final-content"><span className="kicker kicker-gold">ONE MORE BITE?</span><h2>Ready for your<br /><em>next crunch?</em></h2><p>Your new favourite snack is a message away.</p><a className="button button-cream" href={whatsapp()} target="_blank" rel="noopener noreferrer">Order on WhatsApp <ArrowUpRight size={19} /></a></div></section>
    </main>
    <footer className="footer"><div className="shell"><div className="footer-main"><div className="footer-brand"><Brand light /><p>Good food. Better living.<br />Made for everyday enjoyment.</p></div><div className="footer-links"><span>EXPLORE</span><a href="#products">Our Kuli-Kuli</a><a href="#why">Why you’ll love it</a><a href="#process">How it’s made</a><a href="#story">Our story</a></div><div className="footer-links"><span>GET IN TOUCH</span><a href={whatsapp()} target="_blank" rel="noopener noreferrer">Chat on WhatsApp</a><a href="tel:+2348032052940">0803 205 2940</a><a href="mailto:ounjeeh@gmail.com">ounjeeh@gmail.com</a><p>Ilishan-Remo, Ogun State, Nigeria</p></div><div className="footer-signoff"><span>✳</span><p>Made with a little<br />more goodness.</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} OUNJEEH. All rights reserved.</span><span>GOOD FOOD. BETTER LIVING.</span></div></div></footer>
    <a className="floating-whatsapp" href={whatsapp()} target="_blank" rel="noopener noreferrer" aria-label="Chat with OUNJEEH on WhatsApp"><MessageCircle size={23} /><span>Let’s chat</span></a>
  </>;
}
